name: term2048 # you probably want to 'snapcraft register <name>'
version: '0.2.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: 2048 in your terminal
description: |
        term2048 is a terminal-based version of 2048.
        Just like 2048, but in the terminal!
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
        term2048:
                command: bin/term2048

parts:
  term2048:
    # See 'snapcraft plugins'
    source: https://github.com/bfontaine/term2048.git
    source-tag: 0.2.5
    plugin: python
